/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as CounterCounterNumberImport } from './routes/counter.$counterNumber'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CounterCounterNumberRoute = CounterCounterNumberImport.update({
  path: '/counter/$counterNumber',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/counter/$counterNumber': {
      id: '/counter/$counterNumber'
      path: '/counter/$counterNumber'
      fullPath: '/counter/$counterNumber'
      preLoaderRoute: typeof CounterCounterNumberImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  CounterCounterNumberRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/counter/$counterNumber"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/counter/$counterNumber": {
      "filePath": "counter.$counterNumber.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
