/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ExampleImport } from './routes/example'

// Create Virtual Routes

const ExamplelazyLazyImport = createFileRoute('/examplelazy')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ExamplelazyLazyRoute = ExamplelazyLazyImport.update({
  path: '/examplelazy',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/examplelazy.lazy').then((d) => d.Route))

const ExampleRoute = ExampleImport.update({
  path: '/example',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/example': {
      id: '/example'
      path: '/example'
      fullPath: '/example'
      preLoaderRoute: typeof ExampleImport
      parentRoute: typeof rootRoute
    }
    '/examplelazy': {
      id: '/examplelazy'
      path: '/examplelazy'
      fullPath: '/examplelazy'
      preLoaderRoute: typeof ExamplelazyLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  ExampleRoute,
  ExamplelazyLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/example",
        "/examplelazy"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/example": {
      "filePath": "example.tsx"
    },
    "/examplelazy": {
      "filePath": "examplelazy.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
